version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }} 
      - run: yarn bootstrap
      - run: yarn lint
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }} 
      - run: yarn bootstrap
      - run: yarn cov
      - run: bash <(curl -s https://codecov.io/bash)
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }} 
      - run: yarn bootstrap
      - run: yarn build
  docs-deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1e:5d:74:ef:2c:25:11:8c:2c:ee:f8:16:39:ff:22:b9"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - run: git config --global user.email $GH_EMAIL
      - run: git config --global user.name $GH_NAME
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn doc:build
      - run: yarn doc:deploy
      
workflows:
  version: 2
  lint_test_build:
    jobs:
      - lint
      - test
      - build
      - docs-deploy